services:
  db:
    image: postgres:16.2-bookworm
    ports:
      - 5432:5432
    env_file:
      - .env

  kc:
    depends_on:
      - db
    build:
      context: ./kc
    ports:
      - ${KC_HTTP_PORT}:${KC_HTTP_PORT}
    env_file:
      - .env
    command: start --optimized

  react:
    depends_on:
      - kc
    build:
      context: ./react
    ports:
      - '${VITE_PORT}:5173'
    env_file:
      - .env
    volumes:
      - ./react/src:/app/src
