services:
  kc:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

  react:
    build:
      context: ./react
    ports:
      - '5173:5173'
    volumes:
      - ./react/src:/app/src
