services:
  db:
    build:
      context: ./db
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - .env

  kc:
    depends_on:
      - db
    build:
      context: ./kc
    ports:
      - ${KC_HTTP_PORT}:${KC_HTTP_PORT}
    env_file:
      - .env

  mailhog:
    depends_on:
      - kc
    build:
      context: ./mailhog
    ports:
      - ${MH_UI_BIND_ADDR_PORT}:${MH_UI_BIND_ADDR_PORT}
    env_file:
      - .env

  api:
    depends_on:
      - kc
    build:
      context: ./api
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env

  react:
    depends_on:
      - kc
      - api
    build:
      context: ./react
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    env_file:
      - .env
    volumes:
      - ./react/src:/app/src:rw
